services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    ports:
      - 1433:1433

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
